# Utiliza la imagen oficial de nginx-unprivileged
FROM nginxinc/nginx-unprivileged:latest

# Copia el contenido de tu carpeta dist al directorio de nginx
COPY ./dist /usr/share/nginx/html/login

# Exponer el puerto 8080 en lugar del 80 (porque Nginx unprivileged utiliza 8080 por defecto)
EXPOSE 8080

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
